name: "zeta-guard"

networks:
  zeta-guard:
    name: zeta-guard

services:
  keycloak-db:
    image: postgres:17-alpine
    container_name: zeta-guard-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: zeta-guard
      POSTGRES_PASSWORD: geheim
    networks:
      - zeta-guard
    ports:
      - "15432:5432"
    healthcheck:
      test: pg_isready -h localhost -p 5432 -U zeta-guard -d keycloak
      interval: 3s
      timeout: 3s
      retries: 5

  keycloak:
    image: zeta/zeta-guard/keycloak-zeta
    container_name: zeta-guard-keycloak
    environment:
      PRINT_ENV: true
      JAVA_LOCALE: -Duser.timezone=Europe/Berlin
      JAVA_OPTS_APPEND: -ea
      KC_DEBUG: true
      KC_DEBUG_PORT: "*:8787"

      # Put Keycloak build options in the first build stage of the container image
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: zeta-guard
      KC_DB_PASSWORD: geheim
      KC_BOOTSTRAP_ADMIN_USERNAME: zeta
      KC_BOOTSTRAP_ADMIN_PASSWORD: sigma
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: http://localhost:18080
      KC_HTTP_ENABLED: true
      # https://www.informatik-aktuell.de/betrieb/sicherheit/token-exchange-mit-keycloak.html
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_SUCCESS_LEVEL: "info"
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_ERROR_LEVEL: "warn"
      KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_OPA_ENABLED: true
      KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_DECISION_PATH: "/v1/data/policies/zeta/authz/decision"
      KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_OPA_SIMULATION_BASE_URL: "http://opa-simulation:8181"
      # Initial hash for admin events log
      GENESIS_HASH: ${GENESIS_HASH:-4841c2142fef441daa6ee6c57db65c011935964b14e94a6c8f5ec0447b83526c}
      SMCB_HASHING_PEPPER: ${SMCB_HASHING_PEPPER:-085c1245-dc0d-4d39-95b4-97496bec6182}
      # Where to find SMC-B certificates and how to read them
      SMCB_KEYSTORE_LOCATION: /opt/keycloak/conf/smcb-certificates.p12
      SMCB_KEYSTORE_PASSWORD: "tyqvHpFoHdu68yRE+0F4q/I"
      TPM_KEYSTORE_LOCATION: /opt/keycloak/conf/tpm-certificates.p12
      TPM_KEYSTORE_PASSWORD: "O3Bdel9P5+cOgzIGANkOPEzBQM3V"
    ports:
      - "127.0.0.1:18787:8787" # debug port
      - "127.0.0.1:18080:8080" # api port
    networks:
      - zeta-guard
    volumes:
      - ./smcb-certificates.p12:/opt/keycloak/conf/smcb-certificates.p12
      - ./tpm-certificates.p12:/opt/keycloak/conf/tpm-certificates.p12
    healthcheck:
      # No curl in Keycloak 🙄
      test: |
        exec 3<>/dev/tcp/127.0.0.1/9000; printf "GET /health/ready HTTP/1.1\r\nhost: localhost:9000\r\nConnection: close\r\n\r\n" >&3;grep "HTTP/1.1 200 OK" <&3
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      keycloak-db:
        condition: service_healthy
    command: start --log="console,file" --optimized
  # DEBUG Logging
  #--log-level=org.keycloak:DEBUG

  # https://github.com/adorsys/keycloak-config-cli
  keycloak-config-cli:
    image: ${IMAGE_KEYCLOAK_CONFIG:-zeta/zeta-guard/keycloak-config-cli}
    container_name: keycloak-config-cli
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"
      KEYCLOAK_USER: zeta
      KEYCLOAK_PASSWORD: sigma
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 60s
      IMPORT_FILES: "/config/*"
      # See https://github.com/adorsys/keycloak-config-cli?tab=readme-ov-file#variable-substitution
      IMPORT_VARSUBSTITUTION_ENABLED: true
      # See entrypoint.sh
      DEBUG_CLI_SCRIPTS: true
      KC_EVENT_LISTENER: zeta-guard-admin-events
      ADMIN_EVENT_LOGGING_ENABLED: true
      ADMIN_EVENT_LOGGING_DETAILS_ENABLED: true
    networks:
      - zeta-guard
    volumes:
      - ./realms:/config
      - ./scripts-local:/opt/keycloak/scripts
      - ./scripts-repository:/opt/keycloak/scripts-repository

  opa:
    image: openpolicyagent/opa:1.11.0-static
    container_name: zeta-guard-opa
    command:
      - run
      - --server
      - --log-level=info
      - --addr=0.0.0.0:8181
      - --diagnostic-addr=0.0.0.0:8282
      - /bundle
    volumes:
      - ./opa/opa-active:/bundle:ro
    ports:
      - "18181:8181"   # OPA API
      - "18282:8282"   # OPA diagnostics
    networks:
      - zeta-guard

  opa-simulation:
    image: openpolicyagent/opa:1.14.0-static
    container_name: zeta-guard-opa-simulation
    command:
      - run
      - --server
      - --log-level=info
      - --addr=0.0.0.0:8181
      - --diagnostic-addr=0.0.0.0:8282
      - /bundle
    volumes:
      - ./opa/opa-simulation:/bundle:ro
    ports:
      - "18183:8181"   # OPA simulation API
      - "18284:8282"   # OPA simulation diagnostics
    networks:
      - zeta-guard
